
version: '2'

services:
  backup-pg:
    image: 'terrabrasilis/backup-pg-dump:v1.2.0'
    container_name: backup-pg
    restart: always
    volumes:
      - '/main/storage:/data'
    networks:
      - proxy_default

networks:
  proxy_default:
    external: true