
version: '2'

services:
  backup-pg-d:
    image: 'terrabrasilis/backup-pg-dump:v1.4.0'
    container_name: backup-pg-d
    restart: always
    volumes:
      - './src/data:/data'
    environment:
      # if omitted or different from "DAILY" the "WEEKLY" mode will be used.
      - "FREQUENCY=DAILY"
      # the number of days to keep backups and logs. If omitted, defaults are used.
      - "DAYS_TO_KEEP=10"

  backup-pg-w:
    image: 'terrabrasilis/backup-pg-dump:v1.4.0'
    container_name: backup-pg-w
    restart: always
    volumes:
      - './src/data:/data'